server:
  port: 8080
spring:
  datasource:
    name: cloudplatform
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudplatform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  neo4j:
    uri: bolt://10.33.50.19:7687
    authentication:
      username: neo4j
      password: LHY2453369987lhy
# 指定数据库
  data:
    neo4j:
      database: neo4j

